#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building the project before committing'

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check.
    Make the changes required above.'
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo 'ESLint Check Failed. 
    Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check Prettier standards
npm run check-format ||
(
    echo 'Bad styling
    Prettier Check Failed. Run "npm run format", add changes, and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Committing ✅✅✅✅'